services:
  hello-world-service:
    image: 323707565364.dkr.ecr.us-east-1.amazonaws.com/test-compose:latest

x-uffizzi-ingress:
  service: nginx
  port: 8080

x-uffizzi-continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
  
configs:
  my_config_2:
    file: ./config2/vote2.conf
